name: Griffin Boneck
description: Rambling about startups
meta_description: "Griffin's ramblings on startups and other stuff."

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://your-blog-url.example.com'
author:         'Griffin Boneck'
authorTwitter:  'YourTwitterUsername'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
